### ISSUE TITLE
Messages relayed from groupme gets resent

### ISSUE THREAD

**Issue by VBQL** [RhythmLunatic/discord2groupme#12]
I have multiple users on both groupme and discord, is there an option where I can solve the issue described above?

**Comment by VBQL** [comment]
fixed, just put the botid in the userid section

**Comment by matt3948** [comment]
I hate to re-open this but I'm having the exact issue and I attempted to put the botId into the groupme_bot_id but alas - still double posts. Where did you pull the botId from? The only one I can seem to get is the one from the dev portal that is a mix of numbers and letters.

I've tried "allow_all" : "false" and "allow_all" : "true" as well but no luck.

**Comment by RhythmLunatic** [comment]
Sorry, I haven't maintained the bot in a while since I only used it to use discord over SMS. It's been broken for months, last time I just added a hardcoded ID check for my bot because the Discord API was reporting the wrong ID and it was different than what you would get when right clicking the bot name in the Discord client.

**Comment by RhythmLunatic** [comment]
There was a typo in the line that says
`if (require('url').parse(config.discord_webhook_url).pathname.split('/')[2] === message.author.id) return`

This should be 3, not 2.
Anyway I removed the allow_all stuff, I think it was kind of unnecessary
